### PR TITLE
Update the UI for showing time in a better way

### PR DESCRIPTION
**Pull request by Amitgb14**
Closes:#2

### CODE REVIEW

**Comment by Amitgb14** [comment]
@rtnpro please make sure these changes are correct.

**Comment by sayanchowdhury** [comment]
@Amitgb14  can you rebase the branch on top develop?

**Comment by Amitgb14** [comment]
@sayanchowdhury , i think is that ok.

**Comment by Amitgb14** [comment]
@kushaldas, need to be there any changes require?

**Comment by Amitgb14** [comment]
@sayanchowdhury @kushaldas  Reminder

**Comment by sayanchowdhury** [comment]
HI @Amitgb14 

A lot of changes were in progress due to which we did not merge this PR. Right now the development work is going on in the branch `compose-refactor`. Can you update the PR with the changes on top of `compose-refactor` branch?

**Comment by Amitgb14** [comment]
@sayanchowdhury, Yes, I will be update.

**Comment by Amitgb14** [comment]
@sayanchowdhury, This changes comes with `compose-refactor` branch, Try `%A, %d. %B %Y %I:%M%p` syntax, show more better date-time format. I will be close this PR.

**Pull request closed without merging**
